version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=verysecretpassword
      - POSTGRES_USER=DataProcess
      - POSTGRES_DB=DataProcess
    ports:
      - "5432:5432"
